/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type AreaOfWorkReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "areaOfWork";
};

export type ProjectTypeReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "projectType";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  areaOfWork: AreaOfWorkReference;
  projectType?: ProjectTypeReference;
  status: "planned" | "active" | "completed";
  summary: string;
  coverImage: AccessibleImage;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href: string;
          openInNewTab?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        caption?: string;
        credit?: string;
        _type: "projectImage";
        _key: string;
      }
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type AccessibleImage = {
  _type: "accessibleImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  decorative?: boolean;
  alt?: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type ProjectType = {
  _id: string;
  _type: "projectType";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: string;
};

export type AreaOfWork = {
  _id: string;
  _type: "areaOfWork";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: string;
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroHeadline: string;
  heroHighlightedText: string;
  heroDescription: string;
  heroImage: AccessibleImage;
  researchHeading: string;
  researchDescription: string;
  researchMapImage: AccessibleImage;
  researchParticipants: Array<
    {
      _key: string;
    } & NetworkParticipant
  >;
  visionStatement: string;
  missionStatement: string;
  featuredProjectsHeading: string;
  featuredProjects: Array<
    {
      _key: string;
    } & ProjectReference
  >;
};

export type NetworkParticipant = {
  _type: "networkParticipant";
  title: string;
  description: string;
  image: AccessibleImage;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | AreaOfWorkReference
  | ProjectTypeReference
  | SanityImageAssetReference
  | Project
  | SanityImageCrop
  | SanityImageHotspot
  | AccessibleImage
  | Slug
  | ProjectType
  | AreaOfWork
  | ProjectReference
  | HomePage
  | NetworkParticipant
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/sanity/lib/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_type == "homePage" && _id == "homePage"][0] {    _id,    heroHeadline,    heroHighlightedText,    heroDescription,    heroImage {      asset,      crop,      hotspot,      decorative,      alt    },    researchHeading,    researchDescription,    researchMapImage {      asset,      crop,      hotspot,      decorative,      alt    },    researchParticipants[] {      _key,      title,      description,      image {        asset,        crop,        hotspot,        decorative,        alt      }    },    visionStatement,    missionStatement,    featuredProjectsHeading,    featuredProjects[]-> {      _id,      title,      "slug": slug.current,      status,      summary,      coverImage {        asset,        crop,        hotspot,        decorative,        alt      },      areaOfWork-> {        title,        "slug": slug.current      },      projectType-> {        title,        "slug": slug.current      }    }  }
export type HOME_PAGE_QUERY_RESULT = {
  _id: "homePage";
  heroHeadline: string;
  heroHighlightedText: string;
  heroDescription: string;
  heroImage: {
    asset: SanityImageAssetReference | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
    decorative: boolean | null;
    alt: string | null;
  };
  researchHeading: string;
  researchDescription: string;
  researchMapImage: {
    asset: SanityImageAssetReference | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
    decorative: boolean | null;
    alt: string | null;
  };
  researchParticipants: Array<{
    _key: string;
    title: string;
    description: string;
    image: {
      asset: SanityImageAssetReference | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      decorative: boolean | null;
      alt: string | null;
    };
  }>;
  visionStatement: string;
  missionStatement: string;
  featuredProjectsHeading: string;
  featuredProjects: Array<{
    _id: string;
    title: string;
    slug: string;
    status: "active" | "completed" | "planned";
    summary: string;
    coverImage: {
      asset: SanityImageAssetReference | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      decorative: boolean | null;
      alt: string | null;
    };
    areaOfWork: {
      title: string;
      slug: string;
    };
    projectType: {
      title: string;
      slug: string;
    } | null;
  }>;
} | null;

// Source: ../web/sanity/lib/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project" && defined(slug.current)]    | order(_createdAt desc) {      _id,      title,      "slug": slug.current,      status,      summary,      coverImage {        asset,        crop,        hotspot,        decorative,        alt      },      areaOfWork-> {        title,        "slug": slug.current      },      projectType-> {        title,        "slug": slug.current      }    }
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  status: "active" | "completed" | "planned";
  summary: string;
  coverImage: {
    asset: SanityImageAssetReference | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
    decorative: boolean | null;
    alt: string | null;
  };
  areaOfWork: {
    title: string;
    slug: string;
  };
  projectType: {
    title: string;
    slug: string;
  } | null;
}>;

// Source: ../web/sanity/lib/queries.ts
// Variable: PROJECT_BY_SLUG_QUERY
// Query: *[    _type == "project" &&    slug.current == $slug  ][0] {    _id,    title,    "slug": slug.current,    status,    summary,    coverImage {      asset,      crop,      hotspot,      decorative,      alt    },    areaOfWork-> {      title,      "slug": slug.current    },    projectType-> {      title,      "slug": slug.current    },    body[] {      ...,      _type == "projectImage" => {        ...,        asset,        alt,        caption,        credit,        "dimensions": asset->metadata.dimensions,        "lqip": asset->metadata.lqip      }    }  }
export type PROJECT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  status: "active" | "completed" | "planned";
  summary: string;
  coverImage: {
    asset: SanityImageAssetReference | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
    decorative: boolean | null;
    alt: string | null;
  };
  areaOfWork: {
    title: string;
    slug: string;
  };
  projectType: {
    title: string;
    slug: string;
  } | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href: string;
          openInNewTab?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset: SanityImageAssetReference | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        caption: string | null;
        credit: string | null;
        _type: "projectImage";
        _key: string;
        dimensions: SanityImageDimensions | null;
        lqip: string | null;
      }
  >;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "homePage" && _id == "homePage"][0] {\n    _id,\n    heroHeadline,\n    heroHighlightedText,\n    heroDescription,\n    heroImage {\n      asset,\n      crop,\n      hotspot,\n      decorative,\n      alt\n    },\n    researchHeading,\n    researchDescription,\n    researchMapImage {\n      asset,\n      crop,\n      hotspot,\n      decorative,\n      alt\n    },\n    researchParticipants[] {\n      _key,\n      title,\n      description,\n      image {\n        asset,\n        crop,\n        hotspot,\n        decorative,\n        alt\n      }\n    },\n    visionStatement,\n    missionStatement,\n    featuredProjectsHeading,\n    featuredProjects[]-> {\n      _id,\n      title,\n      "slug": slug.current,\n      status,\n      summary,\n      coverImage {\n        asset,\n        crop,\n        hotspot,\n        decorative,\n        alt\n      },\n      areaOfWork-> {\n        title,\n        "slug": slug.current\n      },\n      projectType-> {\n        title,\n        "slug": slug.current\n      }\n    }\n  }\n': HOME_PAGE_QUERY_RESULT;
    '\n  *[_type == "project" && defined(slug.current)]\n    | order(_createdAt desc) {\n      _id,\n      title,\n      "slug": slug.current,\n      status,\n      summary,\n      coverImage {\n        asset,\n        crop,\n        hotspot,\n        decorative,\n        alt\n      },\n      areaOfWork-> {\n        title,\n        "slug": slug.current\n      },\n      projectType-> {\n        title,\n        "slug": slug.current\n      }\n    }\n': PROJECTS_QUERY_RESULT;
    '\n  *[\n    _type == "project" &&\n    slug.current == $slug\n  ][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    status,\n    summary,\n\n    coverImage {\n      asset,\n      crop,\n      hotspot,\n      decorative,\n      alt\n    },\n\n    areaOfWork-> {\n      title,\n      "slug": slug.current\n    },\n\n    projectType-> {\n      title,\n      "slug": slug.current\n    },\n\n    body[] {\n      ...,\n      _type == "projectImage" => {\n        ...,\n        asset,\n        alt,\n        caption,\n        credit,\n        "dimensions": asset->metadata.dimensions,\n        "lqip": asset->metadata.lqip\n      }\n    }\n  }\n': PROJECT_BY_SLUG_QUERY_RESULT;
  }
}
